---
- name: Installing Java {{ java_version }} 
  hosts: web
  become: yes
  vars:
    java_version: '8'
    ansible_python_interpreter: /usr/bin/python3

  tasks: 
   - name: Update apt packages
     apt:
      update_cache: yes 

   - name: Installing Java {{ java_version }}
     apt:
      name: openjdk-{{ java_version }}-jdk
      state: present