---
- name: Recreate Deployment Strategy.. 
  hosts: loadbalancer
  become: yes
  tasks: 
   - name: Stopping Nginx..for maintenance
     service:
      name: nginx
      state: stopped
   
- name: Deploying .war2 file
  hosts: web
  become: yes
  vars:
    tomcat_directory_path: '/opt/tomcat'
    src_war_file: '.'
    tomcat_version: '9.0.45'
  tasks:
   - name: Copying war file to remote server
     copy:
      src: "{{ src_war_file }}/Spring3HibernateApp2.war"
      dest: "{{ tomcat_directory_path }}/apache-tomcat-{{ tomcat_version }}/webapps/Spring3HibernateApp2.war"

- name: Starting Nginx after App is upgraded...
  hosts: loadbalancer
  become: yes
  tasks: 
   - name:
     service:
      name: nginx
      state: started
