---
- name: "Installing Tomcat {{ tomcat_major_version }}"
  hosts: web
  become: yes
  vars:
    java_version: '8'
    tomcat_user: 'tomcat'
    tomcat_group: 'tomcat'
    tomcat_major_version: '9'
    tomcat_version: '9.0.45'
    tomcat_directory_path: '/opt/tomcat'
    tomcat_service_file_path: '.'
    tomcat_password: 'password'
    src_war_file_path: '.'
    ansible_python_interpreter: /usr/bin/python3    
  tasks:
   - name: add Tomcat Group
     group:
      name: "{{ tomcat_group }}"
   
   - name: add Tomcat User
     user:
      name: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
       
   - name: check if tomcat directory exist or not
     stat:
      path: "{{ tomcat_directory_path }}"
     register: stat_result
       
   - name: Creating directory
     file:
      path: "{{ tomcat_directory_path }}"
      state: directory
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: 0700
      recurse: yes
     when: not stat_result.stat.exists
     
   - name: check if tomcat folder exist or not
     stat:
      path: "{{ tomcat_directory_path }}/apache-tomcat-{{ tomcat_version }}"
     register: tomcat_stat_result

   - name: "Download tomcat{{ tomcat_major_version }}"
     unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
      dest: "{{ tomcat_directory_path }}"
      remote_src: yes
      owner: "{{ tomcat_user }}"
     when: not tomcat_stat_result.stat.exists
       
   - name: Change ownership
     file:
      path: "{{ tomcat_directory_path }}/apache-tomcat-{{ tomcat_version }}"
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: 0700
      recurse: yes
      state: directory
 
   - name: Copy Tomcat service file from local to remote
     template:
      src: "{{ tomcat_service_file_path }}/tomcat.service"
      dest: /etc/systemd/system/
      mode: 0700

   - name: Starting Tomcat
     service:
      name: tomcat
      state: started

   - name: Copying war file to remote server
     copy:
      src: "{{ src_war_file_path }}/Spring3HibernateApp.war"
      dest: "{{ tomcat_directory_path }}/apache-tomcat-{{ tomcat_version }}/webapps/ROOT.war"
     notify:
      - Restart and Enable Tomcat

  handlers:
   - name: Restart and Enable Tomcat
     service:
      name: tomcat
      state: restarted
      enabled: true
